language: csharp
mono:
  - latest
  - 3.12.0
  - 3.10.0
script:
  - sudo apt-get install nunit-console
  - nuget restore UtiliyDemoProject.sln
  - xbuild UtiliyDemoProject.sln
  - nunit-console Utility.Test/bin/Debug/Utility.Test.dll